# amin kiani
from email.mime.text import MIMEText
import smtplib

text = """
"""  # ? matn Email ra vared konid.


emailAdress = ''  # ? Example with out @aut.ac.ir
password = ''  # ? your password

EMAILS = ['a.zarebidaki@aut.ac.ir', 'mogharei@aut.ac.ir', 'a_asayesh@aut.ac.ir',
          'e.farrokh@aut.ac.ir', 'afeslami@aut.ac.ir', 'ghaemi@aut.ac.ir',
          'shemshak@aut.ac.ir', 'raie@aut.ac.ir', 'eeas35@aut.ac.ir',
          'tousi@aut.ac.ir', 'naghash@aut.ac.ir', 'keramati@aut.ac.ir',
          'tavakoli@aut.ac.ir', 'eamani@aut.ac.ir', 'ehsanhajizadeh@aut.ac.ir',
          'khamehchi@aut.ac.ir', 'nazerfard@aut.ac.ir', 'aafshar@aut.ac.ir',
          'rahbar@aut.ac.ir', 'tshamsi@aut.ac.ir', 'arefazar@aut.ac.ir',
          'ahmadaku@aut.ac.ir', 'fahim@aut.ac.ir', 'amousavi@aut.ac.ir',
          'nickabadi@aut.ac.ir', 'aakardan@aut.ac.ir', 'raisia@aut.ac.ir',
          'rabbani@aut.ac.ir', 'arshi@aut.ac.ir',
          'deylamia@aut.ac.ir', 'ardehez@aut.ac.ir', 'soufi@aut.ac.ir',
          'islam_ranjbar@aut.ac.ir', 'jamshidi@aut.ac.ir', 'eskhor@aut.ac.ir',
          'eaflaki@aut.ac.ir', 'eskandar@aut.ac.ir', 'alamdari@aut.ac.ir',
          'a_aminisport@aut.ac.ir', 'ashkanbabazadeh@aut.ac.ir', 'ajalali@aut.ac.ir',
          'afrahajizadeh@aut.ac.ir', 'ataghvaei@aut.ac.ir', 'eshakeri@aut.ac.ir',
          'elaheh.jooybar@aut.ac.ir', 'kowsarie@aut.ac.ir', 'naghshineh@aut.ac.ir',
          'ahmadi_javid@aut.ac.ir', 'ajafargholi@aut.ac.ir', 'amir.jahanshahi@aut.ac.ir',
          'a_khorsandi@aut.ac.ir', 'amirah@aut.ac.ir', 'kalbasi@aut.ac.ir',
          'agolroo@aut.ac.ir', 'a-suratgar@aut.ac.ir', 'rezaie@aut.ac.ir',
          'a_azadmehr@aut.ac.ir', 'zarrati@aut.ac.ir', 'a_ghahremani@aut.ac.ir',
          'askarpour@aut.ac.ir', 'akhavan@aut.ac.ir', 'amin.gheibi@aut.ac.ir',
          'madani.en@aut.ac.ir', 'a_esfandiari@aut.ac.ir', 'esfahaa@aut.ac.ir',
          'a.karkhaneh@aut.ac.ir', 'ghorbani@aut.ac.ir', 'sattari@aut.ac.ir',
          'imansharifi@aut.ac.ir', 'shabani@aut.ac.ir', 'i.farahbakhsh@aut.ac.ir',
          'babakb@aut.ac.ir', 'b.khorsandi@aut.ac.ir', 'basadegh@aut.ac.ir',
          'bbakhshi@aut.ac.ir', 'drbdabir@aut.ac.ir', 'rezai@aut.ac.ir',
          'banana@aut.ac.ir', 'arezoo@aut.ac.ir', 'b.behnam@aut.ac.ir',
          'bidabad@aut.ac.ir', 'bkhosravi@aut.ac.ir', 'behrouz@aut.ac.ir',
          'vahidi@aut.ac.ir', 'b.karimi@aut.ac.ir', 'b.baghapour@aut.ac.ir',
          'behzad.najafi@aut.ac.ir', 'arabzadeh@aut.ac.ir', 'bita.zamiri@aut.ac.ir',
          'dariani@aut.ac.ir', 'honari@aut.ac.ir', 'tebadi@aut.ac.ir',
          'ttaghikhany@aut.ac.ir', 'T.eslamkish@aut.ac.ir', 'monfared@aut.ac.ir',
          'fahimpour@aut.ac.ir', 'jamalshahrabi@aut.ac.ir', 'agazad@aut.ac.ir',
          'moghani@aut.ac.ir', 'j.nafardastgerdi@aut.ac.ir', 'shokrani@aut.ac.ir',
          'azarnoush@aut.ac.ir', 'hadibi@aut.ac.ir', 'ghafarirad@aut.ac.ir',
          'farbeh@aut.ac.ir', 'h.mohammadkarimi@aut.ac.ir', 'davoodi@aut.ac.ir',
          'nafisi@aut.ac.ir', 'alebrm@aut.ac.ir', 'adibih@aut.ac.ir',
          'sadeghi@aut.ac.ir', 'hmakki@aut.ac.ir', 'aghaeini@aut.ac.ir',
          'hbasirat@aut.ac.ir', 'hh.monfared@aut.ac.ir', 'verdian@aut.ac.ir',
          'rahimzad@aut.ac.ir', 'rastegar@aut.ac.ir', 'htaheri@aut.ac.ir',
          'ghafoorifard@aut.ac.ir', 'gasemi@aut.ac.ir', 'hsnkato@aut.ac.ir',
          'hafarideh@aut.ac.ir', 'aghahos@aut.ac.ir', 'hhassani@aut.ac.ir',
          'hosseini@aut.ac.ir', 'khaleghi@aut.ac.ir', 'rajaieh@aut.ac.ir',
          'hzeinali@aut.ac.ir', 'h.salaramoli@aut.ac.ir', 'salarih@aut.ac.ir',
          'h_shahverdi@aut.ac.ir', 'abbasi@aut.ac.ir', 'askarian@aut.ac.ir',
          'hossein@aut.ac.ir', 'nazdast@aut.ac.ir', 'pedram@aut.ac.ir',
          'h.kamran.h@aut.ac.ir', 'karami@aut.ac.ir', 'hossein.karimi@aut.ac.ir',
          'yahyaei@aut.ac.ir', 'beyranvand@aut.ac.ir', 'omidvar@aut.ac.ir',
          'hamidp@aut.ac.ir', 'habibiyan@aut.ac.ir', 'hamidz@aut.ac.ir',
          'hsheikh@aut.ac.ir', 'hmodares@aut.ac.ir', 'mirzadeh@aut.ac.ir',
          'hnaderan@aut.ac.ir', 'keshvari@aut.ac.ir', 'kiani@aut.ac.ir',
          'garmabi@aut.ac.ir', 'hamidami@aut.ac.ir', 'ovesy@aut.ac.ir',
          'ramazi@aut.ac.ir', 'h_zarandi@aut.ac.ir', 'shahriari@aut.ac.ir',
          'h.norouzi@aut.ac.ir', 'katoozian@aut.ac.ir', 'alit@aut.ac.ir',
          'madanipour@aut.ac.ir', 'ddrezaey@aut.ac.ir', 'dkiani@aut.ac.ir',
          'iranshahi@aut.ac.ir', 'iraji@aut.ac.ir', 'dbahman@aut.ac.ir',
          'dahafa@aut.ac.ir', 'fadaid@aut.ac.ir', 'kamani@aut.ac.ir',
          'mokhtarij@aut.ac.ir', 'zrahmati@aut.ac.ir', 'satar.mahdevari@aut.ac.ir',
          'fattahi.m.s@aut.ac.ir', 'memaran@aut.ac.ir', 'rzamanian@aut.ac.ir',
          'fesharaki@aut.ac.ir', 'rmb@aut.ac.ir', 'amrollahi@aut.ac.ir',
          'akbarzadeh_341@aut.ac.ir', 'haji@aut.ac.ir', 'hoseinir@aut.ac.ir',
          'ramazani@aut.ac.ir', 'sarraf@aut.ac.ir', 'safa@aut.ac.ir',
          'yaghin@aut.ac.ir', 'rmamalek@aut.ac.ir', 'maknoon@aut.ac.ir',
          'rezanadafi@aut.ac.ir', 'r.karimi13@aut.ac.ir', 'r.imani@aut.ac.ir',
          'halladj@aut.ac.ir', 'bagherzadeh_r@aut.ac.ir', 'moini@aut.ac.ir',
          'gamasaee@aut.ac.ir', 'zahmadi@aut.ac.ir', 'shariati@aut.ac.ir',
          'zmirakhori@aut.ac.ir', 'z.mansoori@aut.ac.ir', 'z_akhlaghi@aut.ac.ir',
          'sarasaeedi@aut.ac.ir', 'sara.malekan@aut.ac.ir', 'sseyedin@aut.ac.ir',
          'shirali@aut.ac.ir', 'sajjad.afraei@aut.ac.ir', 'sajadjafari@aut.ac.ir',
          'sajjad.habibzadeh@aut.ac.ir', 's_noori@aut.ac.ir', 's.sadeghnejad@aut.ac.ir',
          'saadat@aut.ac.ir', 'tafazolian@aut.ac.ir', 'khatami@aut.ac.ir',
          'rezakhah@aut.ac.ir', 'setayesh@aut.ac.ir', 'sharifian_s@aut.ac.ir',
          'saeed@aut.ac.ir', 'shiry@aut.ac.ir', 'saeedss@aut.ac.ir',
          'sa.talebi@aut.ac.ir', 'sderfani@aut.ac.ir', 's.mansour@aut.ac.ir',
          's.nikoosokhan@aut.ac.ir', 'pourmahd@aut.ac.ir', 's.s.tafreshi@aut.ac.ir',
          's.mazinani@aut.ac.ir', 'momtazi@aut.ac.ir', 's.gorji@aut.ac.ir',
          'niksefat@aut.ac.ir', 'akbari_s@aut.ac.ir', 'sajavadi@aut.ac.ir',
          'nourazar@aut.ac.ir', 'epackachis@aut.ac.ir', 'khorsandi@aut.ac.ir',
          'hmadani@aut.ac.ir', 'srm@aut.ac.ir', 'a.hejazi@aut.ac.ir',
          'esmailifar@aut.ac.ir', 'smr.shahabi@aut.ac.ir', 'mirzapour@aut.ac.ir',
          'mmesbah@aut.ac.ir', 'imani@aut.ac.ir', 'nhashemi@aut.ac.ir',
          'h.mofidi@aut.ac.ir', 'mirdehghan@aut.ac.ir', 'banifatemi@aut.ac.ir',
          'mirsalehi@aut.ac.ir', 'motamedi@aut.ac.ir', 'kashi@aut.ac.ir',
          'jmosavi@aut.ac.ir', 'mirkhalili@aut.ac.ir', 'khoshrou@aut.ac.ir',
          'ghodsypo@aut.ac.ir', 'hamirsha@aut.ac.ir', 'hosseinian@aut.ac.ir',
          'hmousavi@aut.ac.ir', 'fathi@aut.ac.ir', 'shahabi@aut.ac.ir',
          'sr_ghaffarian@aut.ac.ir', 's.ghannadpour@aut.ac.ir', 'a.hashemi@aut.ac.ir',
          'ssalehi@aut.ac.ir', 'sadough@aut.ac.ir', 'moussavi@aut.ac.ir',
          'a_mirhassani@aut.ac.ir', 'sa.hashemi@aut.ac.ir', 'mirsalim@aut.ac.ir',
          'smmirhos@aut.ac.ir', 'mmohseni@aut.ac.ir', 'm_moshrefi@aut.ac.ir',
          'sma@aut.ac.ir', 'varkiyan@aut.ac.ir', 'elham@aut.ac.ir',
          'moattarh@aut.ac.ir', 'mmousavi@aut.ac.ir', 'fatemi@aut.ac.ir',
          'hashemee@aut.ac.ir', 'smhmirbagheri@aut.ac.ir', 'hkarim@aut.ac.ir',
          'rimam@aut.ac.ir', 'alavi@aut.ac.ir', 'mrhashemigolpayegani@aut.ac.ir',
          'm.etemad@aut.ac.ir', 'mo_mirsalim@aut.ac.ir', 'msafavi@aut.ac.ir',
          'vaez@aut.ac.ir', 'smrezaei@aut.ac.ir', 'msaviz@aut.ac.ir',
          'marashi@aut.ac.ir', 'tabaian@aut.ac.ir', 'hajirb@aut.ac.ir',
          'pmarashi@aut.ac.ir', 'nikravsh@aut.ac.ir', 's.bagheri@aut.ac.ir',
          'stahouni@aut.ac.ir', 'bayati@aut.ac.ir', 'ahanjan@aut.ac.ir',
          'smontom@aut.ac.ir', 'sh.fazel@aut.ac.ir', 'semami@aut.ac.ir',
          'fariborz@aut.ac.ir', 'shahlashekarriz@aut.ac.ir', 'ssaramad@aut.ac.ir',
          'satarahom@aut.ac.ir', 'sadegh@aut.ac.ir', 'srezaei@aut.ac.ir',
          's.firoozi@aut.ac.ir', 'seyedena@aut.ac.ir', 'moeiniae@aut.ac.ir',
          'kaghazch@aut.ac.ir', 't.h.hejazi@aut.ac.ir', 'tgoudarzi@aut.ac.ir',
          'adel@aut.ac.ir', 'behzadif@aut.ac.ir', 'atefeh.solouk@aut.ac.ir',
          'abbas.ahmadi@aut.ac.ir', 'afrazeh@aut.ac.ir', 'a_sarsharzadeh@aut.ac.ir',
          'soroush@aut.ac.ir', 'aseifi@aut.ac.ir', 'abbassi@aut.ac.ir',
          'abm125@aut.ac.ir', 'a.maghsoudi@aut.ac.ir', 'naderifar@aut.ac.ir',
          'nasiraei@aut.ac.ir', 'hsadeghi@aut.ac.ir', 'javaherian@aut.ac.ir',
          'arpabbas@aut.ac.ir', 'aroujali@aut.ac.ir', 'a_r_ohadi@aut.ac.ir',
           'abdipour@aut.ac.ir', 'ardeshir@aut.ac.ir',
          'asadri@aut.ac.ir', 'erfan.salavati@aut.ac.ir', 'ajavadi@aut.ac.ir',
          'a.aghaz@aut.ac.ir', 'aliazimi@aut.ac.ir', 'ali.ahmadpour@aut.ac.ir',
          'ajeddi@aut.ac.ir', 'altofigh@aut.ac.ir', 'roghani@aut.ac.ir',
          'sarabi@aut.ac.ir', 'sabbagh_alvani@aut.ac.ir', 'katbab@aut.ac.ir',
          'aaramce@aut.ac.ir', 'azarei@aut.ac.ir', 'abdzad@aut.ac.ir',
          'aghaji@aut.ac.ir', 'merati@aut.ac.ir', 'alibavali@aut.ac.ir',
          'alihatam@aut.ac.ir', 'khodaii@aut.ac.ir', 'dad@aut.ac.ir',
          'moghaddamjoo@aut.ac.ir', 'shamsipur@aut.ac.ir', 'sal1358@aut.ac.ir',
          'farzadi@aut.ac.ir', 'afallah@aut.ac.ir', 'mohades@aut.ac.ir',
          'kimiagar@aut.ac.ir', 'ali.madadi@aut.ac.ir', 'ali.mortazavi@aut.ac.ir',
          'anikbakht@aut.ac.ir', 'kargari@aut.ac.ir', 'alikamalie@aut.ac.ir',
          'arebrahimi@aut.ac.ir', 'ar_bagheri@aut.ac.ir', 'ajahan@aut.ac.ir',
          'a.khosravi@aut.ac.ir', 'rahai@aut.ac.ir', 'a.sheikh@aut.ac.ir',
          'sadeghirad@aut.ac.ir', 'afallahi@aut.ac.ir', 'mahjub@aut.ac.ir',
          'mofidi@aut.ac.ir', 'kazemia@aut.ac.ir', 'sahlodin@aut.ac.ir',
          'gh.rezvani@aut.ac.ir', 'gholam@aut.ac.ir', 'grouhi@aut.ac.ir',
          'ghmoradi@aut.ac.ir', 'havaei@aut.ac.ir', 'ghpazuki@aut.ac.ir',
          'f_hoseinian@aut.ac.ir', 'jalilsan@aut.ac.ir', 'dadashia@aut.ac.ir',
          'f.zare@aut.ac.ir', 'f.shakeri@aut.ac.ir', 'f_mousazadegan@aut.ac.ir',
          'f.nami@aut.ac.ir', 'goharpey@aut.ac.ir', 'moztarzadeh@aut.ac.ir',
          'afshar@aut.ac.ir', 'khoshnud@aut.ac.ir', 'fmoodi@aut.ac.ir',
          'marsusi@aut.ac.ir', 'Towhidkhah@aut.ac.ir', 'hatami@aut.ac.ir',
          'didehvar@aut.ac.ir', 'mahboubi@aut.ac.ir', 'f_dehghan@aut.ac.ir',
          'fshayeganfar@aut.ac.ir', 'f_abdollahi@aut.ac.ir', 'far@aut.ac.ir',
          'zokaee@aut.ac.ir', 'almas@aut.ac.ir', 'fbarazandeh@aut.ac.ir',
          'ghassemi@aut.ac.ir', 'f.hooshmand.khaligh@aut.ac.ir', 'namin_farhad@aut.ac.ir',
          'javan@aut.ac.ir', 'frahmati@aut.ac.ir', 'sharif@aut.ac.ir',
          'f.sabery@aut.ac.ir', 'f.fakhar@aut.ac.ir', 'orang@aut.ac.ir',
          'rashidi@aut.ac.ir', 'biglari@aut.ac.ir', 'moghadas@aut.ac.ir',
          'baktiari@aut.ac.ir', 'zargarzadeh@aut.ac.ir', 'leilanaji@aut.ac.ir',
          'l.azadani@aut.ac.ir', 'masakb@aut.ac.ir', 'mnaderi@aut.ac.ir',
          'pysham@aut.ac.ir', 'mojtaba@aut.ac.ir', 'mozaffar@aut.ac.ir',
          'mjnayeri@aut.ac.ir', 'shalchian@aut.ac.ir', 'mavval@aut.ac.ir',
          'mjohari@aut.ac.ir', 'phdabdouss44@aut.ac.ir', 'map60@aut.ac.ir',
          'ghasemi@aut.ac.ir', 'tex5mm@aut.ac.ir', 'akbarpour@aut.ac.ir',
          'mbahrami@aut.ac.ir', 'tehranizadeh@aut.ac.ir', 'mo.khajehzadeh@aut.ac.ir',
          'rezaeian@aut.ac.ir', 'sajadieh@aut.ac.ir', 'moezzi@aut.ac.ir',
          'm.karrabi@aut.ac.ir', 'm.ahmady@aut.ac.ir', 'edrisi@aut.ac.ir',
          'amani@aut.ac.ir', 'akbari.ma@aut.ac.ir', 'tafazoli@aut.ac.ir',
          'ameri@aut.ac.ir', 'mj.emadi@aut.ac.ir', 'ghaffari@aut.ac.ir',
          'mousazadeh@aut.ac.ir', 'm.razbin@aut.ac.ir', 'mhoseini@aut.ac.ir',
          'mhkish@aut.ac.ir', 'mrabiee@aut.ac.ir', 'm.rahmani@aut.ac.ir',
          'rahmati@aut.ac.ir', 'mrezaei@aut.ac.ir', 'mzare@aut.ac.ir',
          'mohammad.saeedi@aut.ac.ir', 'm_sharifi@aut.ac.ir', 'aghdam@aut.ac.ir',
          'maroufi@aut.ac.ir', 'm.moeini@aut.ac.ir', 'mmahmadi@aut.ac.ir',
          'mehrafar@aut.ac.ir', 'milaei@aut.ac.ir', 'mkarimi@aut.ac.ir',
          'myavari@aut.ac.ir', 'shiri@aut.ac.ir', 'm.a.khosravi@aut.ac.ir',
          'fayzi@aut.ac.ir', 'menhaj@aut.ac.ir', 'banki@aut.ac.ir',
          'mkermani@aut.ac.ir', 'hafezi@aut.ac.ir', 'jmotamed@aut.ac.ir',
          'ketabdar@aut.ac.ir', 'sebt@aut.ac.ir', 'hshirali@aut.ac.ir',
          'mhmoradi@aut.ac.ir', 'zarandi@aut.ac.ir', 'namazi@aut.ac.ir',
          'eslami@aut.ac.ir', 'rezaeslami@aut.ac.ir', 'akbari.pe@aut.ac.ir',
          'babaei@aut.ac.ir', 'hajmohammadi@aut.ac.ir', 'mrnobari@aut.ac.ir',
          'khedmati@aut.ac.ir', 'm.khorsand@aut.ac.ir', 'razfar@aut.ac.ir',
          'razzazi@aut.ac.ir', 'msadeghi@aut.ac.ir', 'hesami@aut.ac.ir',
          'mojtahed@aut.ac.ir', 'attar@aut.ac.ir', 'mmeybodi@aut.ac.ir',
          'a33@aut.ac.ir', 'mzkabir@aut.ac.ir', 'pajouh@aut.ac.ir',
          'tavanaie@aut.ac.ir', 'salari@aut.ac.ir', 'ebadzadeh@aut.ac.ir',
          'm.alinia@aut.ac.ir', 'mahdi.lotfi@aut.ac.ir', 'homayoun@aut.ac.ir',
          'maghsudi@aut.ac.ir', 'sadr@aut.ac.ir', 'alipour2@aut.ac.ir',
          'akbarif@aut.ac.ir', 'shakeri@aut.ac.ir', 'm.abbasi@aut.ac.ir',
          'mghiasi@aut.ac.ir', 'mani@aut.ac.ir', 'momtazpour@aut.ac.ir',
          'arami@aut.ac.ir', 'ebrahimi@aut.ac.ir', 'mortezahabibi@aut.ac.ir',
          'mo.zamanian@aut.ac.ir', 'sohrabi@aut.ac.ir', 'szamani@aut.ac.ir',
          'saba@aut.ac.ir', 'osanloo@aut.ac.ir', 'ardehali@aut.ac.ir',
          'mmreza@aut.ac.ir', 'mklhdzan@aut.ac.ir', 'khatib@aut.ac.ir',
          'parvandi@aut.ac.ir', 'Ashrafi.mm@aut.ac.ir', 'mazlaghani@aut.ac.ir',
          'mfani@aut.ac.ir', 'mghsaryazdi@aut.ac.ir', 'yousefzadeh@aut.ac.ir',
          'boromand@aut.ac.ir', 'mshafiee@aut.ac.ir', 'sabaei@aut.ac.ir',
          'mazizi@aut.ac.ir', 'latifi@aut.ac.ir', 'mmahootchi@aut.ac.ir',
          'mpourmahd@aut.ac.ir', 'msaybani@aut.ac.ir', 'm-mohajeri@aut.ac.ir',
          'mo.ahmadi@aut.ac.ir', 'mostafa.chehreghani@aut.ac.ir', 'rostami@aut.ac.ir',
          'm_shamsi@aut.ac.ir', 'm.abbaszadeh@aut.ac.ir', 'ketabchi@aut.ac.ir',
          'moraveji@aut.ac.ir', 'haghbin@aut.ac.ir', 'mohamadian@aut.ac.ir',
          'm_nabaei@aut.ac.ir', 'farsi@aut.ac.ir', 'peydyesh@aut.ac.ir',
          'kabgan@aut.ac.ir', 'mkalbasi@aut.ac.ir', 'soleimanim@aut.ac.ir',
          'ghanbar@aut.ac.ir', 'khorasani.m@aut.ac.ir', 'msalehi@aut.ac.ir',
          'fadavie@aut.ac.ir', 'nikazar@aut.ac.ir', 'mahdi.tohidian@aut.ac.ir',
          'maebrahimi@aut.ac.ir', 'mehdi.ahmadi@aut.ac.ir', 'ahmadin@aut.ac.ir',
          'makhlagi@aut.ac.ir', 'iranajad@aut.ac.ir', 'imehdi@aut.ac.ir',
          'bostanshirin@aut.ac.ir', 'mbanazadeh@aut.ac.ir', 'hashemi@aut.ac.ir',
          'khakian@aut.ac.ir', 'mdehghan@aut.ac.ir', 'dehghan@aut.ac.ir',
          'rasti@aut.ac.ir', 'mross@aut.ac.ir', 'mehdi@aut.ac.ir',
          'sabzeh@aut.ac.ir', 'kiasat@aut.ac.ir', 'mshajari@aut.ac.ir',
          'mehdi.shabani@aut.ac.ir', 'shafieian@aut.ac.ir', 'msedighi@aut.ac.ir',
          'salaynaderi@aut.ac.ir', 'ghatee@aut.ac.ir', 'majidpour@aut.ac.ir',
          'karrari@aut.ac.ir', 'm.golparvar@aut.ac.ir', 'mtadjfar@aut.ac.ir',
          'javanbakht@aut.ac.ir', 'msfallah@aut.ac.ir', 'solati@aut.ac.ir',
          'mkasra@aut.ac.ir', 'abedi@aut.ac.ir', 'mozaffarian@aut.ac.ir',
          'mJahandideh@aut.ac.ir', 'eskandarim@aut.ac.ir', 'shamshir@aut.ac.ir',
          'naraghi@aut.ac.ir', 'dadvar@aut.ac.ir', 'otaghsara@aut.ac.ir',
          'msesfahani@aut.ac.ir', 'habibian@aut.ac.ir', 'miladrezaei@aut.ac.ir',
          'aminghafari@aut.ac.ir', 'mntzrn@aut.ac.ir', 'nparvin@aut.ac.ir',
          'ezazshahabi@aut.ac.ir', 'nrtavana@aut.ac.ir', 'broojerd@aut.ac.ir',
          'nshams@aut.ac.ir', 'nasser@aut.ac.ir', 'mohamadi@aut.ac.ir',
          'nsheikhan@aut.ac.ir', 'hemmati@aut.ac.ir', 'nabolfathi@aut.ac.ir',
          'nfallah2001@aut.ac.ir', 'azarnia@aut.ac.ir', 'nrabiei@aut.ac.ir',
          'ashari@aut.ac.ir', 'atrianfar@aut.ac.ir', 'hadishirali@aut.ac.ir',
          'dabiryan@aut.ac.ir', 'hadi_mosadegh@aut.ac.ir', 'hd.miri@aut.ac.ir',
          'nakhai@aut.ac.ir', 'aliabadi@aut.ac.ir', 'eslamih@aut.ac.ir',
          'asempour@aut.ac.ir', 'katibeh@aut.ac.ir', 'araghi@aut.ac.ir',
          'hnosraty@aut.ac.ir', 'hnoshad@aut.ac.ir', 'vmaleki@aut.ac.ir',
          'haddadi@aut.ac.ir', 'shahhosseini@aut.ac.ir', 'vahlotfi@aut.ac.ir',
          'v.pourahmadi@aut.ac.ir', 'pghadimi@aut.ac.ir', 'parvizz@aut.ac.ir',
          'pnx@aut.ac.ir', 'parvin@aut.ac.ir', 'pdehkhoda@aut.ac.ir',
          'phajikarimi@aut.ac.ir', 'p.hoseinpour@aut.ac.ir', 'payam.tehrani@aut.ac.ir',
          'kfakhari@aut.ac.ir', 'dehghani@aut.ac.ir', 'k_raissi@aut.ac.ir',
          'mansour@aut.ac.ir', 'mirabbas@aut.ac.ir', 'cyrusk@aut.ac.ir',
          'c.falamaki@aut.ac.ir', 'kfaez@aut.ac.ir', 'shahver@aut.ac.ir',
          'k.shahriar@aut.ac.ir', 'kmanochehri@aut.ac.ir', 'gsadeghi@aut.ac.ir',
          'grptian@aut.ac.ir', 'y.norouzi@aut.ac.ir', 'y.rohani@aut.ac.ir',
          'amirarj@aut.ac.ir', 'y.rafiei@aut.ac.ir', 'alizadeh@aut.ac.ir',
          'm.sedighi@aut.ac.ir', 'ajafari@aut.ac.ir', ]


def sendMail(emailAdress: str, password: str, text: str):
    if emailAdress.endswith('@aut.ac.ir'):
        emailAdress = emailAdress.split('@')[0]
    if emailAdress.endswith('@gmail.com') or emailAdress.endswith('@yahoo.com.com'):
        print('lotfan email danshjooye khod ra vared konid')
        return
    try:
        msg = MIMEText(text)
        s = smtplib.SMTP('mail.aut.ac.ir', 587)
        s.login(emailAdress,password)
        s.starttls()
        # s.debuglevel(1)
        counter = 1
        for email in EMAILS:
            try:
                msg = MIMEText(text)
                msg['Subject'] = 'درباره ی ...'
                msg['From'] = f'{emailAdress}@aut.ac.ir'
                msg['To'] = ', '.join((email,))
                s.sendmail(emailAdress+'@aut.ac.ir',
                        email, msg.as_string())
                
                print('%d/%d: %s'%(counter,len(EMAILS),email))
                counter +=1
            except Exception as e:
                print(e)
                s.close()
                if 'connect' in str(e):
                    s = smtplib.SMTP('mail.aut.ac.ir', 587)
                    s.login(emailAdress,password)
                    s.starttls()
        s.close()

    except Exception as e:
        print(e)


sendMail(emailAdress, password, text)
